SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600

BIRD_SIZE = 40
PIPE_WIDTH = BIRD_SIZE * 2
PIPE_GAP_HEIGHT = BIRD_SIZE * 4.5

PIPE_SPEED = 10
FALL_SPEED = 10
JUMP_SPEED = 15

NUM_ACTIONS = 2

GAP_BOUNDARY = SCREEN_HEIGHT / 4

ACTION_DICT = {0:False, 1:True}